openapi: 3.0.0
info:
  title: News App API
  version: 1.0.0
  description: API documentation for News App

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /api/articles:
    get:
      summary: List articles
      responses:
        '200':
          description: Successful response

components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        category_id:
          type: integer
        created_at:
          type: string
          format: date-time
    
    Pagination:
      type: object
      properties:
        current_page:
          type: integer
        total:
          type: integer
        per_page:
          type: integer